In [2]:
import numpy as np
import sys
import importlib
sys.path.append("..")
import utils.effective_monitoring_time


In [4]:
np.zeros(10) > np.zeros(10)

array([False, False, False, False, False, False, False, False, False,
       False])

In [7]:
mjds = np.arange(12)
filters = np.array(['u', 'g', 'r'] * 4)
exptimes = np.zeros(12)
exposure_ends = mjds + exptimes
taus = np.array([0.99, 1., 3., 20.])

In [62]:
importlib.reload(utils.effective_monitoring_time)

scanner = utils.effective_monitoring_time.LcScanner(taus, n_filters_req=3)

In [63]:
scanner._setup(mjds, filters)

In [64]:
scanner._record_windows(mjds, filters, exposure_ends)

[ -0.99  -1.    -3.   -20.  ]
[0 0 0 0]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[1 1 1 1]
[ 1.0e-02  0.0e+00 -2.0e+00 -1.9e+01]
[0. 0. 0. 0.]
[1 2 1 1]
[ 1.0e-02  1.0e+00 -2.0e+00 -1.9e+01]
[0. 0. 0. 0.]
[2 2 1 1]
[  1.01   1.    -2.   -19.  ]
[0.01 0.   1.   1.  ]
[2 3 1 1]
[  1.   2.  -3. -20.]
[1. 1. 2. 2.]
[3 3 1 1]
[  1.01   1.    -4.   -21.  ]
[1.01 1.   3.   3.  ]
[3 4 1 1]
[  1.   2.  -5. -22.]
[2. 2. 4. 4.]
[4 4 1 1]
[  1.01   1.    -6.   -23.  ]
[2.01 2.   5.   5.  ]
[4 5 1 1]
[  1.   2.  -7. -24.]
[3. 3. 6. 6.]
[5 5 1 1]
[  1.01   1.    -8.   -25.  ]
[3.01 3.   7.   7.  ]
[5 6 1 1]
[  1.   2.  -9. -26.]
[4. 4. 8. 8.]
[6 6 1 1]
[  1.01   1.   -10.   -27.  ]


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [30]:
delta_t_start = (mjds[scanner.state.time.start_idx] -
                 scanner.state.time.t_start)

In [31]:
smaller = delta_t_start < scanner._delta_t_end(mjds)

In [32]:
t_idx_shift = np.where(smaller, 1, 0)

In [33]:
next_filter_idx = np.where(smaller,
                           scanner.state.time.start_idx,
                           scanner.state.time.end_idx)
# Get the next filter using these idxs.
next_filter = filters[next_filter_idx]
filter_number = scanner.filter_map(next_filter)
# If the next filter is outgoing (smaller_delta_t_start) subtract from
# n_filters_bright and add to n_filters_baseline
filter_shift = np.where(smaller, -1, 1)

In [34]:
scanner._shift_window(exposure_ends, t_idx_shift, filter_shift, filter_number)

In [43]:
scanner._record_t_start()

array([nan, nan, nan, nan])