In [91]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datalab_utils
import astropy.units as u

from dl import authClient as ac, queryClient as qc
from collections import Counter
from tqdm import tqdm

plt.rcParams['axes.facecolor']='white'
plt.rcParams['savefig.facecolor']='white'
fig_dir = "/dlusers/adriansh/work/analyses/plots/strings/"

In [100]:
lc_df = pd.concat([pd.read_parquet(f"/dlusers/adriansh/work/analyses/results/strings/june12_2024/lightcurves_batch{i}.parquet") for i in range(10)])
lc_df.reset_index(inplace=True, drop=True)

In [120]:
import importlib
importlib.reload(datalab_utils)
results_df = datalab_utils.make_lensing_dataframe(lc_df)

In [121]:
results_df

t_start         t_end filters
objectid                                           
180653_2368   0  56279.191628  56282.179140      gr
180654_5092   0  56265.334668  56267.304445      iz
180293_1766   0  56311.129536  56311.132751      iz
179930_2434   0  56311.129536  56311.133590     izY
179930_5541   0  56267.309984  56267.312551      zY
...                       ...           ...     ...
187553_58813  0  57432.095451  57432.113815      ug
187554_116545 0  57432.094424  57432.113815     uuu
187554_120213 0  57432.093387  57432.110386     uuu
187551_53682  0  58526.065904  58791.151554      rr
187550_51827  0  58553.116224  58791.154203      rg

[958 rows x 3 columns]

In [118]:
z = np.zeros(10)
z[[1, 2, 3]] = 1
zb = z.astype(bool)
zb, ~zb

(array([False,  True,  True,  True, False, False, False, False, False,
        False]),
 array([ True, False, False, False,  True,  True,  True,  True,  True,
         True]))

In [119]:
%timeit z == 1
%timeit z.astype(bool)

1.34 µs ± 7.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
476 ns ± 1.89 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [80]:
n_total = 20
baseline_idxs = np.array([2, 3, 4, 5, 7, 8, 9, 10, 15, 16, 17])
baseline = np.zeros(n_total)
baseline[baseline_idxs] = 1

In [82]:
baseline[:] = 1
baseline[0] = 0

In [83]:
t_end = [i+1 for i in all_idxs[:-1] if baseline[i] == 0 and baseline[i+1] == 1]

In [84]:
t_start = [i for i in all_idxs[:-1] if baseline[i] == 1 and baseline[i+1] == 0]

In [85]:
if baseline[0] == 0:
    t_start = np.concatenate([[np.nan], t_start])
if baseline[-1] == 0:
    t_end = np.concatenate([t_end, [np.nan]])

In [86]:
np.column_stack([t_start, t_end])

array([[nan,  1.]])

In [90]:
np.arange(10).reshape(5, 2)[1:, 1]

array([3, 5, 7, 9])